### ISSUE TITLE
Broken indentation when altering MsSQL function

### ISSUE THREAD

**Issue by sg2002** [alex-hhh/emacs-sql-indent#40]
I've crystalized this use case from a function I recently had to write:
```
USE [testdb]
  GO
  SET ANSI_NULLS ON
  GO
  SET QUOTED_IDENTIFIER ON
  GO
  ALTER FUNCTION [dbo].[Test]
  ()
  RETURNS
  @TestBatch TABLE
  (
    [param] [varchar](20) NOT NULL,
    [param2] [datetime] NOT NULL,
    )
  AS
  BEGIN
    DECLARE @var int;
      DECLARE @var2 int;
        set @var = 100;
        RETURN
          END
```

The ideal would be:
```
USE [testdb]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[Test]
()
RETURN
@TestBatch TABLE
(
    [param] [varchar](20) NOT NULL,
    [param2] [datetime] NOT NULL,
)
AS
BEGIN
    DECLARE @var int;
    DECLARE @var2 int;
    set @var = 100;
    RETURN
END
```

**Comment by alex-hhh** [comment]
I pushed some changes to fix the syntax recognition for MsSQL declare keyword as well as the directives.  The SQL sample you gave is now correctly recognized, but the indentation for the function declaration part will not match your example, because the defaults are different.  

To get it to indent the way you showed in the example, you will need to update your indentation rules as follows:

```elisp
(defvar pr40-indentation-offsets-alist
  `((defun-start 0)
    (nested-statement-continuation
     sqlind-lineup-into-nested-statement
     sqlind-lineup-close-paren-to-open)
    ,@sqlind-default-indentation-offsets-alist))
(add-hook 'sqlind-mode-hook
            (lambda ()
              (setq sqlind-indentation-offsets-alist
                    pr40-indentation-offsets-alist)))
```

For more details on how to customize the indentation rules, see the [sql-indent.org](../blob/master/sql-indent.org) file

**Comment by sg2002** [comment]
I wanted to report that the hook is actually named sqlind-minor-mode-hook, but I just noticed that you already fixed it in the documentation.

And thanks for working on this mode. Having indentation in SQL really gives Emacs another edge.
