### ISSUE TITLE
`align` separates multi-char comparison operators, changing meaning

### ISSUE THREAD

**Issue by brendan-r** [alex-hhh/emacs-sql-indent#47]
Calling `align` on a statement such as

```sql
select
  blah
from
  blah
where
  foo = 3 and
  bar >= 40 and
  foobar < 9 and
  barfoo != 42
```

produces

```sql
select
  blah
from
  blah
where
  foo      = 3 and
  bar >    = 40 and
  foobar < 9 and
  barfoo ! = 42
```

Separating the `>/!` and the `=` changes the meaning of the statement, which is undesirable! An ideal (but complicated) result might be something like

```sql
select
  blah
from
  blah
where
  foo    =  3  and
  bar    >= 40 and
  foobar <  9  and
  barfoo != 42
```

**Comment by alex-hhh** [comment]
The use case you showed was not supported by the existing alignment rules, but because of a bug in a different alignment rule it was doing the wrong thing.  

I pushed a fix for your use case, although the "and" keywords are not aligned. @PierreTechoueyres might have some more experience as he worked on the existing ones, he might have an idea on how to align the "and" keywords.

Alignment rules are more fragile and difficult to debug, it would be good to have some automated tests around that area.  Also, I'm not very experienced with them.

**Comment by brendan-r** [comment]
The fix works perfectly with 

```
emacs -batch -Q --no-site-file -L . -l sql-indent.el
```

But not with my config, even with all minor modes disabled and custom sqlindent code removed. I'll follow up in #45 to contain the discussion.

**Comment by brendan-r** [comment]
Commits above fix issue; failure to reproduce success was user error. Many thanks!
