### ISSUE TITLE
"left outer" not recognised as join by sqlind-lineup-joins-to-anchor

### ISSUE THREAD

**Issue by dandavison** [alex-hhh/emacs-sql-indent#85]
Similar to #73, would it make sense to modify the regexp in `sqlind-lineup-joins-to-anchor` so that `left outer` and `right outer` are recognised? I made that change locally and was able to achieve the indentation I was after.

**Comment by alex-hhh** [comment]
I will not have time to look into this in the next two weeks or so, but I will get to it eventually.

**Comment by alex-hhh** [comment]
I had a brief look at the problem, and I believe adding them to `sqlind-lineup-joins-to-anchor` is incorrect and only works if the "left outer join" statement is at the beginning of the line -- I understand that this is sufficient for you, but in general the code needs to determine a correct anchor point for this case.

The "outer" keywords need to be added to `sqlind-select-join-regexp` but this is somewhat tricky as these are two words and the code will need to be extended to look backwards one or two words.  This is needed in order to compute the anchor point of the JOIN statement correctly.

**Comment by alex-hhh** [comment]
I pushed a fix for this, can you test and see if it works for you? Thanks, Alex.

**Comment by dandavison** [comment]
Yes, I can confirm that this works for me. (In that `(left|right) outer join` now indent the same as `inner join` at 47e9ccb). Thank you!
